import PDFDocument from "pdfkit";

export const generatePdf = async (data) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: 50,
      info: {
        Author: "PowerAI",
        Title: data.title,
        Creator: "PowerAI",
      },
    });

    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", () => reject);

    //   title

    doc
      .fontSize(28)
      .text(data.title, {
        align: "center",
      })
      .fillColor("#11827");

    if (data.subtitle) {
      doc.moveDown(0.5);
    }

    //   subtitle

    doc
      .fontSize(12)
      .text(data.subtitle, {
        align: "center",
      })
      .fillColor("#6B7280");

    doc.moveDown(2);

    data?.section?.forEach((s) => {

      doc.fillColor("#11827")
      .fontSize(18)
      .text(s.heading)

      doc.moveDown(0.5);

      s?.points?.forEach((p) => {
          doc
          .fillColor("#374151")
          .fontSize(12)
          .text(`• ${p}`, {
            lineGap: 5,
            indent:10,
          });
        })
        ;

      doc.moveDown();
    });

    doc
      .fontSize(10)
      .text("Generated By PowerAI", {
        align: "center",
      })
      .fillColor("#9CA3AF");

      doc.end()
  });
};
